[General]
network = test_project.usingStandardProtocols.SimpleNetwork
sim-time-limit = 10ms


**.router1.forwarding = true
**.router1.ipv4.typename = "inet.networklayer.ipv4.Ipv4NetworkLayer"
#**.router.ipv4.typename = "test_project.usingStandardProtocols.CustomIpLayer"
**.router1.ipv4.ip.typename = "test_project.usingStandardProtocols.CustomNetworkLayer"
#**.router.eth[*].typename = "test_project.usingStandardProtocols.CustomEthernetInterface"
**.router1.eth[*].queue.typename = "test_project.usingStandardProtocols.CustomQueue"

**.router1.eth[*].queue.packetCapacity = 100
**.router1.eth[*].queue.dropperClass = "RandomPacketDropper"
**.router1.eth[*].queue.scheduler = "ljf"
#**.router.eth[*].scheduler.schedulerClass = "inet::queueing::PacketLengthScheduler"
#**.router.eth[*].queue.scheduler.schedulerClass = "inet::queueing::PacketLengthScheduler"
#**.router.ipv4.ip.typename = "inet.networklayer.ipv4.Ipv4"
#**.router.ipv4.natTable.networkProtocolModule = "^.ip"
#**.router.ipv4.arp.interfaceTableModule = "^.interfaceTable"
#**.router.ipv4.arp.routingTableModule = "^.routingTable"
#**.router.interfaceTable = "^.interfaceTable"
**.router1.numEthInterfaces = 4
**.router2.numEthInterfaces = 4
**.standardRouter.numEthInterfaces = 3
**.client1.numEthInterfaces = 1
**.client2.numEthInterfaces = 1
**.client3.numEthInterfaces = 1
**.server1.numEthInterfaces = 1
**.server2.numEthInterfaces = 1

#**.client.interfaceTable.displayAddresses = 
**.router2.forwarding = true
**.router2.ipv4.typename = "inet.networklayer.ipv4.Ipv4NetworkLayer"
#**.router.ipv4.typename = "test_project.usingStandardProtocols.CustomIpLayer"
**.router2.ipv4.ip.typename = "test_project.usingStandardProtocols.CustomNetworkLayer"
#**.router.eth[*].typename = "test_project.usingStandardProtocols.CustomEthernetInterface"
**.router2.eth[*].queue.typename = "test_project.usingStandardProtocols.CustomQueue"

**.router2.eth[*].queue.packetCapacity = 100
**.router2.eth[*].queue.dropperClass = "RandomPacketDropper"
**.router2.eth[*].queue.scheduler = "ljf"


**.client1.numApps = 1
#**.client.app[0].typename = "test_project.usingStandardProtocols.ClientApp"
**.client1.app[0].typename = "test_project.usingStandardProtocols.CustomUdpApp"
**.client1.app[0].destAddresses = "server1"
**.client1.app[0].destPort = 5000
**.client1.app[0].minMessageLength = 512B
**.client1.app[0].maxMessageLength = 1024B
**.client1.app[0].messageLength = 1024B #Dummy
**.client1.app[0].startTime = 0s
**.client1.app[0].sendInterval = 0.2ms


**.client2.numApps = 1
#**.client.app[0].typename = "test_project.usingStandardProtocols.ClientApp"
**.client2.app[0].typename = "test_project.usingStandardProtocols.CustomUdpApp"
**.client2.app[0].destAddresses = "server1"
**.client2.app[0].destPort = 5000
**.client2.app[0].minMessageLength = 512B
**.client2.app[0].maxMessageLength = 1024B
**.client2.app[0].messageLength = 1024B #Dummy
**.client2.app[0].startTime = 0s
**.client2.app[0].sendInterval = 0.2ms

**.client3.numApps = 1
#**.client.app[0].typename = "test_project.usingStandardProtocols.ClientApp"
**.client3.app[0].typename = "inet.applications.udpapp.UdpBasicApp"
**.client3.app[0].destAddresses = "server2"
**.client3.app[0].destPort = 5000
**.client3.app[0].messageLength = 1024B
**.client3.app[0].startTime = 0s
**.client3.app[0].sendInterval = 2ms

**.server1.numApps = 1
#**.server.app[0].typename = "test_project.usingStandardProtocols.ServerApp"
**.server1.app[0].typename = "inet.applications.udpapp.UdpSink"
**.server1.app[0].localPort = 5000

**.server2.numApps = 1
#**.server.app[0].typename = "test_project.usingStandardProtocols.ServerApp"
**.server2.app[0].typename = "inet.applications.udpapp.UdpSink"
**.server2.app[0].localPort = 5000

#**.configurator.config = xmldoc("config.xml")

#**.configurator.assignDisjunctSubnetAddresses = false
#**.configurator.assignAddresses = false


**.vector-recording = true
**.scalar-recording = true
**.statistic-recording = true



