[General]
network = test_project.usingStandardProtocols.TreeTopology
sim-time-limit = 500ms


**.router1.numEthInterfaces = 4
**.router2.numEthInterfaces = 4
**.centralRouter.numEthInterfaces = 3
**.client1.numEthInterfaces = 1
**.client2.numEthInterfaces = 1
**.client3.numEthInterfaces = 1
**.client4.numEthInterfaces = 1
**.client5.numEthInterfaces = 1
**.client6.numEthInterfaces = 1
**.server.numEthInterfaces = 1


#*.schedulerList = ${sch= "fifo", "random", "lifo", "rr", "sjf", "ljf"}
*.schedulerList = ${sch= "random"}

repeat = 10


**.router1.forwarding = true
**.router1.ipv4.typename = "inet.networklayer.ipv4.Ipv4NetworkLayer"
**.router1.ipv4.ip.typename = "test_project.usingStandardProtocols.CustomNetworkLayer"
**.router1.eth[*].queue.typename = "test_project.usingStandardProtocols.CustomQueue"
**.router1.eth[*].queue.packetCapacity = 100
**.router1.eth[*].queue.dropperClass = "RandomPacketDropper"
**.router1.eth[*].queue.scheduler = ${sch}


**.centralRouter.forwarding = true
**.centralRouter.ipv4.typename = "inet.networklayer.ipv4.Ipv4NetworkLayer"
**.centralRouter.ipv4.ip.typename = "test_project.usingStandardProtocols.CustomNetworkLayer"
**.centralRouter.eth[*].queue.typename = "test_project.usingStandardProtocols.CustomQueue"
**.centralRouter.eth[*].queue.packetCapacity = 100
**.centralRouter.eth[*].queue.dropperClass = "RandomPacketDropper"
**.centralRouter.eth[*].queue.scheduler = ${sch}


**.router2.forwarding = true
**.router2.ipv4.typename = "inet.networklayer.ipv4.Ipv4NetworkLayer"
**.router2.ipv4.ip.typename = "test_project.usingStandardProtocols.CustomNetworkLayer"
**.router2.eth[*].queue.typename = "test_project.usingStandardProtocols.CustomQueue"
**.router2.eth[*].queue.packetCapacity = 100
**.router2.eth[*].queue.dropperClass = "RandomPacketDropper"
**.router2.eth[*].queue.scheduler = ${sch}


**.client1.numApps = 1
**.client1.app[0].typename = "test_project.usingStandardProtocols.CustomUdpApp"
**.client1.app[0].destAddresses = "server"
**.client1.app[0].destPort = 5000
**.client1.app[0].minMessageLength = 512B
**.client1.app[0].maxMessageLength = 1024B
**.client1.app[0].messageLength = 1024B #Dummy
**.client1.app[0].startTime = 0s
**.client1.app[0].sendInterval = 2ms


**.client2.numApps = 1
**.client2.app[0].typename = "test_project.usingStandardProtocols.CustomUdpApp"
**.client2.app[0].destAddresses = "server"
**.client2.app[0].destPort = 5000
**.client2.app[0].minMessageLength = 512B
**.client2.app[0].maxMessageLength = 1024B
**.client2.app[0].messageLength = 1024B #Dummy
**.client2.app[0].startTime = 0s
**.client2.app[0].sendInterval = 2ms

**.client3.numApps = 1
**.client3.app[0].typename = "inet.applications.udpapp.UdpBasicApp"
**.client3.app[0].destAddresses = "server"
**.client3.app[0].destPort = 5000
**.client3.app[0].minMessageLength = 512B
**.client3.app[0].maxMessageLength = 1024B
**.client3.app[0].messageLength = 1024B
**.client3.app[0].startTime = 0s
**.client3.app[0].sendInterval = 2ms


**.client4.numApps = 1
**.client4.app[0].typename = "test_project.usingStandardProtocols.CustomUdpApp"
**.client4.app[0].destAddresses = "server"
**.client4.app[0].destPort = 5000
**.client4.app[0].minMessageLength = 512B
**.client4.app[0].maxMessageLength = 1024B
**.client4.app[0].messageLength = 1024B #Dummy
**.client4.app[0].startTime = 0s
**.client4.app[0].sendInterval = 2ms


**.client5.numApps = 1
**.client5.app[0].typename = "test_project.usingStandardProtocols.CustomUdpApp"
**.client5.app[0].destAddresses = "server"
**.client5.app[0].destPort = 5000
**.client5.app[0].minMessageLength = 512B
**.client5.app[0].maxMessageLength = 1024B
**.client5.app[0].messageLength = 1024B #Dummy
**.client5.app[0].startTime = 0s
**.client5.app[0].sendInterval = 2ms

**.client6.numApps = 1
**.client6.app[0].typename = "inet.applications.udpapp.UdpBasicApp"
**.client6.app[0].destAddresses = "server"
**.client6.app[0].destPort = 5000
**.client6.app[0].minMessageLength = 512B
**.client6.app[0].maxMessageLength = 1024B
**.client6.app[0].messageLength = 1024B
**.client6.app[0].startTime = 0s
**.client6.app[0].sendInterval = 2ms

**.server.numApps = 1
**.server.app[0].typename = "inet.applications.udpapp.UdpSink"
**.server.app[0].localPort = 5000

**.vector-recording = true
**.scalar-recording = true
**.statistic-recording = true



